### ISSUE TITLE
HomePage.ux HitModeTest

### ISSUE THREAD

**Issue by idkjs** [fusetools/hikr#2] opened 2016-10-23 10:52 UTC
El Capitain, Fuse .26
# Issue

Seems like, in local preview, none of the edits to Triggers and animation are work. I tried, for example changing Duration to 2 and removing the Quadractic easing. I did not test this on a device.
# Regarding HitTestMode

Clicked activates from anywhere in the panel regardless of whether HitModeTest is called. If you delete HitModeTest, you get the same action. Doesnt seem like this is expected from your tutorial. 

To be explicit, both of these code samples work the same when tested.
# Without HitModeTest

```
<Page ux:Class="HomePage">
    <Router ux:Dependency="router" />
    <JavaScript File="HomePage.js" />
    <ScrollView>
        <StackPanel>
            <Each Items="{hikes}">
                <Panel Clicked="{goToHike}">
                    <Text Value="{name}" />
                </Panel>
            </Each>
        </StackPanel>
    </ScrollView>
</Page>
```
# With HitModeTest

```
<Page ux:Class="HomePage">
    <Router ux:Dependency="router" />
    <JavaScript File="HomePage.js" />
    <ScrollView>
        <StackPanel>
            <Each Items="{hikes}">
                <Panel HitTestMode="LocalBoundsAndChildren" Clicked="{goToHike}">
                    <Text Value="{name}" />
                </Panel>
            </Each>
        </StackPanel>
    </ScrollView>
</Page>
```

**Comment by eksperts** [comment] 2017-02-27 15:32
Gave all this a thorough test, none of it stands true.
Changing the `HitTestMode` on the list item panel does have the intended effect.
Changing the `Duration` and `Easing` on the `Scale` trigger does have the intended effect, too.

OSX, Fuse 0.35.0.10867, Local preview.

I suggest closing the issue.

**Comment by kristianhasselknippe** [comment] 2017-02-27 15:42
closing this based on @eksperts suggestion. Thanks a lot @idkjs for the ticked and sorry for forgetting about it. This was might have a been caused by a bug in Fuse that got fixed since.

**Closed as completed by kristianhasselknippe** 2017-02-27 15:42 UTC
